// Auto-generated file - DO NOT EDIT
export type IconName = 
 | 'FileText'
 | 'CircleX'
 | 'BarChartBig'
 | 'Menu'
 | 'Parrot'
 | 'AlertTriangle'
 | 'Sun'
 | 'FlagBrazil'
 | 'FlagUSA'
 | 'Table'
 | 'Bot'
 | 'Sparkles'
 | 'LoadingTadpole'
 | 'MessageSquare'
 | 'Moon'
 | 'TrendingUp'
 | 'LoadingBlocks'
 | 'FolderTree'
 | 'Upload'
 | 'Calendar'
 | 'Target'
 | 'LineChart'
